# This config is equivalent to both the '.circleci/extended/orb-free.yml' and the base '.circleci/config.yml'
version: 2.1

# Orbs are reusable packages of CircleCI configuration that you may share across projects, enabling you to create encapsulated, parameterized commands, jobs, and executors that can be used across multiple projects.
# See: https://circleci.com/docs/2.0/orb-intro/
orbs:
  node: circleci/node@4.7

# Invoke jobs via workflows
# See: https://circleci.com/docs/2.0/configuration-reference/#workflows
workflows:
  sample: # This is the name of the workflow, feel free to change it to better match your workflow.
    # Inside the workflow, you define the jobs you want to run.
    jobs:
      - node/test:
          # This is the node version to use for the `cimg/node` tag
          # Relevant tags can be found on the CircleCI Developer Hub
          # https://circleci.com/developer/images/image/cimg/node
          version: "16.10"
          # If you are using yarn, change the line below from "npm" to "yarn"
          pkg-manager: npm
        docker:
          image: circleci/node@4.7
   
        build-docker:
          machine: true
          steps:
            - checkout
            - run:
                name: Build docker container for each Microservice
                command: |
                  echo "==================Installing dependencies================"

                  sudo curl -LO https://nodejs.org/dist/v18.0.0/node-v18.0.0-linux-x64.tar.xz
                  sudo tar xvf node-v18.0.0-linux-x64.tar.xz
                  sudo cp -r node-v18.0.0-linux-x64/{bin,include,lib,share}/user/
                  node --version =>v18.0.0
                  docker build -t udagram-api-feed ./udagram-api-feed
                  docker tag udagram-api-feed ahmedhussin/udagram-api-feed:v1
                  docker build -t udagram-api-user ./udagram-api-user
                  docker tag udagram-api-user ahmedhussin/udagram-api-user:v1
                  docker build -t udagram-frontend ./udagram-frontend
                  docker tag udagram-frontend ahmedhussin/udagram-frontend:v1
                  docker build -t reverseproxy ./reverseproxy
                  docker tag reverseproxy ahmedhussin/reverseproxy:v1

                  echo "----------all images are build ------------- "

                  echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

                  echo "----------Push to DockerHub ------------- "
                  docker push ahmedhussin/udagram-api-feed:v1
                  docker push ahmedhussin/udagram-api-user:v1
                  docker push ahmedhussin/udagram-frontend:v1
                  docker push ahmedhussin/reverseproxy:v1
